### ISSUE TITLE
Fix tab highlight

### ISSUE THREAD

**Issue by ai** [logux/logux-status#17]
Seems like just adding `*` is not enough. Seems like we need to add `*` and remove it every second.

http://stackoverflow.com/questions/37122/make-browser-window-blink-in-task-bar

@andrewmnlv do you want to make it better?

**Comment by ai** [comment]
Now we have a webpage to test Logux Status behaviour in real life: `yarn run demo`

**Comment by andrewmnlv** [comment]
@ai np. i'll add it on days

**Comment by ai** [comment]
@andrewmnlv great work!
